SchoolAdmin/SchoolAdmin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("base.urls", namespace='base')),
    path('announcement/', include("announcement.urls", namespace='announcement')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SchoolAdmin/announcement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views
app_name = 'announcement'

urlpatterns = [
    path('', views.AnnouncementList.as_view(), name='announcement'),
    
    path('create_announcement/', views.CreateAnnouncement.as_view(), name='create_announcement'),
    path('delete_announcement/<int:pk>', views.DeleteAnnouncement.as_view(), name='delete_announcement'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SchoolAdmin/base/urls.py
from django.urls import path
from . import views

app_name = 'base'


urlpatterns = [
    path('', views.home, name="home"),
    path('dashboard/', views.dashboard, name="dashboard"),

    path('student_academics/', views.student_academics, name='student_academics'),
    path('teacher_academics/', views.teacher_academics, name='teacher_academics'),
    
    path('restricted/', views.restricted_view, name='restricted'),
    path('student_login/', views.student_login, name='student_login'),
    path('teacher_login/', views.teacher_login, name='teacher_login'),
    path('staff_login/', views.staff_login, name='staff_login'),
    path('parent_login/', views.parent_login, name='parent_login'),
    path('logout/', views.logout_view, name='logout'),

    path('student_register/', views.student_register, name='student_register'),
    path('teacher_register/', views.teacher_register, name='teacher_register'),
    path('parent_register/', views.parent_register, name='parent_register'),
    path('staff_register/', views.staff_register, name='staff_register'),


    path('student_register_with_file/', views.student_register_with_file, name='student_register_with_file'),
    path('teacher_register_with_file/', views.teacher_register_with_file, name='teacher_register_with_file'),

    path('student_dashboard/<str:grade>', views.student_dashboard, name='student_dashboard'),
    path('teacher_dashboard/', views.teacher_dashboard, name='teacher_dashboard'),
    path('staff_dashboard/', views.staff_dashboard, name='staff_dashboard'),
    path('parent_dashboard/', views.parent_dashboard, name='parent_dashboard'),


    path('result_dashboard/<str:grade>', views.result_dashboard, name='result_dashboard'),
    path('publish_result/', views.publish_result, name='publish_result'),


    path('student_update/<str:pk>', views.student_update, name='student_update'),
    path('teacher_update/<str:pk>', views.teacher_update, name='teacher_update'),
    path('parent_update/<str:pk>', views.parent_update, name='parent_update'),
    path('staff_update/<str:pk>', views.staff_update, name='staff_update'),


    path('student_profile/<str:pk>', views.student_profile, name='student_profile'),
    path('parent_profile/<str:pk>', views.parent_profile, name='parent_profile'),

    path('change_password', views.change_password, name='change_password'),
]

SchoolAdmin/base/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, HttpResponse, redirect, HttpResponsePermanentRedirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.models import User
from .models import *
from .forms import *
from .utils import *
from openpyxl import load_workbook

# Create your views here.

# base views section
def home(request):
    students = Student.objects.all()
    teachers = Teacher.objects.all()
    staffs = Staff.objects.all()

    female_students = Student.filter_by_gender('F')
    male_students = Student.filter_by_gender('M')

    female_teachers = Teacher.filter_by_gender('F')
    male_teachers = Teacher.filter_by_gender('M')
    
    female_staffs = Staff.filter_by_gender('F')
    male_staffs = Staff.filter_by_gender('M')
    
    context = {
        'teachers': teachers,
        'students': students,
        'staffs': staffs,

        'female_students': female_students,
        'male_students': male_students,

        'female_teachers': female_teachers,
        'male_teachers': male_teachers,

        'female_staffs': female_staffs,
        'male_staffs': male_staffs,
    }

    return render(request, 'base/home.html', context)


@login_required(login_url='/restricted/')
def student_academics(request):
    students = Student.objects.all()
    female = Student.filter_by_gender('F')
    male = Student.filter_by_gender('M')
    context = {
        'students': students,
        'female': female,
        'male': male,
    }

    return render(request, 'student_academics.html', context)

@login_required(login_url='/restricted/')
def teacher_academics(request):
    teachers = Teacher.objects.all()
    female = Teacher.filter_by_gender('F')
    male = Teacher.filter_by_gender('M')
    context = {
        'teachers': teachers,
        'female': female,
        'male': male,
    }
    return render(request, 'teacher_academics.html', context)



# Authentication views section
def logout_view(request):
    logout(request)

    return HttpResponsePermanentRedirect(reverse('base:home'))

def student_login(request):
    if request.method == 'POST':
        student_id = request.POST['student_id']
        password = request.POST['password']

        user = authenticate(request, student_id=student_id, password=password)
        if user:
            login(request, user)
            return redirect('base:home')
        else:
            error_message = 'Invalid ID number or Password'
            return render(request, 'login/student_login.html', {'error_message': error_message})
    else:
        return render(request, 'login/student_login.html')

def teacher_login(request):
    if request.method == 'POST':
        teacher_id = request.POST['teacher_id']
        password = request.POST['password']

        user = authenticate(request, teacher_id=teacher_id, password=password)
        if user:
            login(request, user)
            return redirect('base:home')
        else:
            error_message = 'Invalid ID number or Password'
            return render(request, 'login/teacher_login.html', {'error_message': error_message})
    else:
        return render(request, 'login/teacher_login.html')

def staff_login(request):
    if request.method == 'POST':
        staff_id = request.POST['staff_id']
        password = request.POST['password']

        user = authenticate(request, staff_id=staff_id, password=password)
        if user:
            login(request, user)
            if user.is_staff:
                return redirect('base:dashboard')
            else:
                return redirect('base:home')
        else:
            error_message = 'Invalid ID number or Password'
            return render(request, 'login/staff_login.html', {'error_message': error_message})
    else:
        return render(request, 'login/staff_login.html')

def parent_login(request):
    if request.method == 'POST':
        parent_id = request.POST['parent_id']
        password = request.POST['password']

        user = authenticate(request, parent_id=parent_id, password=password)
        if user:
            login(request, user)
            return redirect('base:home')
        else:
            error_message = 'Invalid ID number or Password'
            return render(request, 'login/parent_login.html', {'error_message': error_message})
    else:
        return render(request, 'login/parent_login.html')


@login_required
def change_password(request):
    if request.method == 'POST':
        current_password = request.POST['current_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']

        user = authenticate(username=request.user.username, password=current_password)
        if user:
            if new_password == confirm_password:
                user.set_password(new_password)
                user.save()
                login(request, user)
                messages.success(request, 'Password is successfully!')
                return redirect('base:home')
            else:
                messages.error(request, 'The New Password and Confirm Password do not match!')
                return redirect('base:change_password')
        else:
            messages.error(request, 'Wrong Password. Please try again!')
            return redirect('base:change_password')

    return render(request, 'dashboard/change_password.html')



# Dashboard Views section
@login_required
@user_passes_test(lambda user: user.is_staff)
def dashboard(request):
    students = Student.objects.all()
    teachers = Teacher.objects.all()
    staffs = Staff.objects.all()
    parents = Parent.objects.all()

    female_students = Student.filter_by_gender('F')
    male_students = Student.filter_by_gender('M')

    female_teachers = Teacher.filter_by_gender('F')
    male_teachers = Teacher.filter_by_gender('M')
    
    female_staffs = Staff.filter_by_gender('F')
    male_staffs = Staff.filter_by_gender('M')
    
    context = {
        'teachers': teachers,
        'students': students,
        'staffs': staffs,
        'parents': parents,

        'female_students': female_students,
        'male_students': male_students,

        'female_teachers': female_teachers,
        'male_teachers': male_teachers,

        'female_staffs': female_staffs,
        'male_staffs': male_staffs,
    }
    return render(request, 'dashboard/dashboard.html', context)



@login_required
@user_passes_test(lambda user: user.is_staff)
def student_dashboard(request, grade='all'):
    students = Student.objects.filter(grade=grade)
    if grade == 'all':
        students = Student.objects.all()
    students = students.order_by('name')
    context = {
        'students': students,
    }
    return render(request, 'dashboard/student_dashboard.html', context)


@login_required
@user_passes_test(lambda user: user.is_staff)
def teacher_dashboard(request):
    teachers = Teacher.objects.order_by('name')
    context = {
        'teachers': teachers,
    }
    return render(request, 'dashboard/teacher_dashboard.html', context)


@login_required
@user_passes_test(lambda user: user.is_staff)
def staff_dashboard(request):
    staffs = Staff.objects.order_by('name')
    context = {
        'staffs': staffs,
    }
    return render(request, 'dashboard/staff_dashboard.html', context)

@login_required
@user_passes_test(lambda user: user.is_staff)
def parent_dashboard(request):
    parents = Parent.objects.order_by('name')
    context = {
        'parents': parents,
    }
    return render(request, 'dashboard/parent_dashboard.html', context)


@login_required
@user_passes_test(lambda user: user.is_staff)
def student_register(request):
    if request.method == 'POST':
        form = StudentCreationForm(request.POST, request.FILES)
        if form.is_valid():
            print(form)
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            email = form.cleaned_data.get('email')
            username = first_name.strip().lower() + '_' + last_name.strip().lower()

            if User.objects.filter(username=username).exists():
                messages.error(request, f'{username} is already registered. Please choose a different username.')
            else:
                user = User.objects.create_user(
                    username=username, 
                    first_name=first_name, 
                    last_name=last_name,
                    email=email,
                    password='@@aa12345',
                )
                if user:
                    name = first_name + ' ' + last_name
                    image = form.cleaned_data['image']
                    grade = form.cleaned_data.get('grade')
                    age = form.cleaned_data.get('age')
                    gender = form.cleaned_data.get('gender')
                    parent_phone = form.cleaned_data.get('parent_phone')
                    student = Student(
                        user=user, 
                        name=name, 
                        image=image,
                        grade=grade, 
                        gender=gender,
                        age=age,
                        parent_phone=parent_phone,
                    )
                    if student:
                        student.save()
                        messages.success(request, f'{name} is registered successfully!')
                        return redirect('base:dashboard')
                    else:
                        user.delete()
                        messages.error(request, 'Someting went wrong while registering Student')
                        
                return redirect('base:student_register')
        else:
            messages.error(request, 'Someting went wrong while registering Student')
    else:

SchoolAdmin/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    
</head>
<body class="d-flex flex-column min-vh-100">
    {% include 'base/navigation.html' %}
    
    {% block content %}
    {% endblock %}

    
    {% include 'base/footer.html' %}
    <script>
        '{% if request.user.is_staff %}'
            var staff = 'True'
        '{% else %}'
            var staff = 'Flase'
        '{% endif %}'
    </script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

SchoolAdmin/base/templates/base/footer.html
<footer class="mt-auto bg-dark text-light bg-secondary ">
    <div class="container">
      <p class="text-center">
        <i>Copyright 2023</i>
      </p>
    </div>
</footer>

SchoolAdmin/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} MTA School {% endblock %}

{% block content %}

{% for message in messages %}
  <div class="alert {%if message.tags == 'success' %} alert-success {% else %} alert-danger {% endif %}">
      {{ message }}
  </div>
{% endfor %}

<!-- Hero section -->
<div id="carouselExampleCaptions" class="carousel slide max-height-550" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active" data-bs-interval="5000">
        <img src="{% static 'image/placeholder.png' %}" class="d-block w-100 max-height-500" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>First slide label</h5>
          <p>Some representative placeholder content for the first slide.</p>
        </div>
      </div>
      <div class="carousel-item" data-bs-interval="5000">
        <img src="{% static 'image/placeholder.png' %}" class="d-block w-100 max-height-500" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Second slide label</h5>
          <p>Some representative placeholder content for the second slide.</p>
        </div>
      </div>
      <div class="carousel-item" data-bs-interval="5000">
        <img src="{% static 'image/placeholder.png' %}" class="d-block w-100 max-height-500" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5>Third slide label</h5>
          <p>Some representative placeholder content for the third slide.</p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
</div>

<!-- About section -->
<div class="container text-center p-4">
    <h1>About Us</h1>
    <div class="row row-cols-1 row-cols-md-2 py-4 rounded shadow-xlg">
        <div class="col">
            <img src="{% static 'image/placeholder.png' %}" alt="Example Image" class="d-block img-fluid rounded" alt="...">
        </div>
        <div class="col">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias quis distinctio 
            dolores quisquam provident voluptatum ad odit unde natus ullam. Recusandae, provident.</p>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. In debitis ullam,
             dolor quia sunt voluptatem optio alias tempora exercitationem, eius ratione possimus.</p>
        </div>
    </div>
</div>

<!-- Insight section -->
<div class="container text-center p-4">
  <h1>Get Insight</h1>
  <div class="container">
    <div class="row justify-content-center row-cols-1 row-cols-sm-2 row-cols-md-3 gy-sm-1 g-4">
      <div class="col d-flex justify-content-center align-items-center">
        <div class="card shadow-xlg rounded h-100 mr-auto ml-auto " style="max-width: 18rem;" >
          <img src="{% static 'image/placeholder.png' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in
               to additional content. This content is a little bit longer.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
      <div class="col d-flex justify-content-center align-items-center">
        <div class="card shadow-xlg h-100" style="max-width: 18rem;">
          <img src="{% static 'image/placeholder.png' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
      <div class="col d-flex justify-content-center align-items-center">
        <div class="card shadow-xlg h-100" style="max-width: 18rem;">
          <img src="{% static 'image/placeholder.png' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- Statistics section -->
<div class="bg-primary">
  <div class="container text-center p-4 text-light">
    <h1>2015 Statistcs</h1>
    <table class="table">
            <thead class="table-primary">
            <tr>
                <th scope="col">Occupation</th>
                <th scope="col">All</th>
                <th scope="col">Males</th>
                <th scope="col">Females</th>
            </tr>
            </thead>
            <tbody>
              <tr class="dashboard-row" href="{% url 'base:student_dashboard' 'all' %}">
                  <td>Students</td>
                  <td>{{ students.count }}</td>
                  <td>{{ male_students.count }}</td>
                  <td>{{ female_students.count }}</td>
              </tr>
              <tr class="dashboard-row" href="{% url 'base:teacher_dashboard'%}">
                    <td>Teachers</td>
                    <td>{{ teachers.count }}</td>
                    <td>{{ male_teachers.count }}</td>
                    <td>{{ female_teachers.count }}</td>
                </tr>
                <tr class="dashboard-row" href="{% url 'base:staff_dashboard' %}">
                    <td>Staffs</td>
                    <td>{{ staffs.count }}</td>
                    <td>{{ male_staffs.count }}</td>
                    <td>{{ female_staffs.count }}</td>
                </tr>
            </tbody>
        </table>
  </div>
</div>

{% endblock %}

SchoolAdmin/base/templates/base/navigation.html
<nav class="navbar sticky-top navbar-expand-lg bg-dark">
    <div class="container">
        <a class="navbar-brand text-light" href="{% url 'base:home' %}">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link text-light active text-light" aria-current="page" href="{% url 'base:home' %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Academics
                    </a>
                    <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'base:student_academics' %}">Student</a></li>
                    <li><a class="dropdown-item" href="{% url 'base:teacher_academics' %}">Teacher</a></li>
                    </ul>
                </li>
                <li class="nav-item" data-bs-toggle="tooltip"  data-bs-placement="bottom" data-bs-title="Coming Soon...">
                    <a class="nav-link text-light" href="#">Blog</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link text-light" href="{% url 'announcement:announcement' %}">Announcements</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link text-light" href="#">Events</a>
                </li>
                </li>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="#">About Us</a>
                </li>
                {% if user.is_staff %}
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'base:dashboard' %}">Dashboard</a>
                </li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link text-primary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fa fa-user" aria-hidden="true"> {{user.username}} </i> 
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% if user.student %}
                                <a class="dropdown-item" href="{% url 'base:student_profile' user.student.student_id %}">Profile</a>
                            {% elif user.teacher %}
                                <a class="dropdown-item" href="{% url 'base:student_profile' user.teacher.teacher_id %}">Profile</a>
                            {% elif user.parent %}
                                <a class="dropdown-item" href="{% url 'base:parent_profile' user.parent.parent_id %}">Profile</a>
                            {% endif %}
                            <a class="dropdown-item" href="{% url 'base:change_password' %}">Change Password</a>
                            <a class="dropdown-item" href="{% url 'base:logout' %}">Logout</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item dropdown">
                        <a class="nav-link text-danger dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Login
                        </a>
                        <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'base:student_login' %}">Student</a></li>
                        <li><a class="dropdown-item" href="{% url 'base:teacher_login' %}">Teacher</a></li>
                        <li><a class="dropdown-item" href="{% url 'base:parent_login' %}">Parent</a></li>
                        <li><a class="dropdown-item" href="{% url 'base:staff_login' %}">Staff</a></li>
                        </ul>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

SchoolAdmin/base/templates/base/restricted.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} MTA School {% endblock %}

{% block content %}

<h3 class="text-light text-center bg-danger">You have to login to access this page</h3>
<div class="container d-flex justify-content-center">
    <div class="p-4 col-9 mt-5 shadow-lg">
      <h2 class="mb-4 text-center">Choose to Login</h2>
      <div class="row justify-content-around">
        <a href="{% url 'base:student_login' %}" class="col-5 btn btn-primary m-1">Student</a>
        <a href="{% url 'base:teacher_login' %}" class="col-5 btn btn-primary m-1">Teacher</a>
        <a href="{% url 'base:parent_login' %}" class="col-5 btn btn-primary m-1">Parent</a>
        <a href="{% url 'base:staff_login' %}" class="col-5 btn btn-primary m-1">Staff</a>
      </div>
    </div>
  </div>
{% endblock %}