SchoolAdmin/SchoolAdmin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("base.urls", namespace='base')),
    path('announcement/', include("announcement.urls", namespace='announcement')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SchoolAdmin/announcement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from . import views
app_name = 'announcement'

urlpatterns = [
    path('', views.AnnouncementList.as_view(), name='announcement'),
    
    path('create_announcement/', views.CreateAnnouncement.as_view(), name='create_announcement'),
    path('delete_announcement/<int:pk>', views.DeleteAnnouncement.as_view(), name='delete_announcement'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SchoolAdmin/base/urls.py
from django.urls import path
from . import views

app_name = 'base'


urlpatterns = [
    path('', views.home, name="home"),
    path('dashboard/', views.dashboard, name="dashboard"),

    path('student_academics/', views.student_academics, name='student_academics'),
    path('teacher_academics/', views.teacher_academics, name='teacher_academics'),
    
    path('restricted/', views.restricted_view, name='restricted'),
    path('student_login/', views.student_login, name='student_login'),
    path('teacher_login/', views.teacher_login, name='teacher_login'),
    path('staff_login/', views.staff_login, name='staff_login'),
    path('parent_login/', views.parent_login, name='parent_login'),
    path('logout/', views.logout_view, name='logout'),

    path('student_register/', views.student_register, name='student_register'),
    path('teacher_register/', views.teacher_register, name='teacher_register'),
    path('parent_register/', views.parent_register, name='parent_register'),
    path('staff_register/', views.staff_register, name='staff_register'),


    path('student_register_with_file/', views.student_register_with_file, name='student_register_with_file'),
    path('teacher_register_with_file/', views.teacher_register_with_file, name='teacher_register_with_file'),

    path('student_dashboard/<str:grade>', views.student_dashboard, name='student_dashboard'),
    path('teacher_dashboard/', views.teacher_dashboard, name='teacher_dashboard'),
    path('staff_dashboard/', views.staff_dashboard, name='staff_dashboard'),
    path('parent_dashboard/', views.parent_dashboard, name='parent_dashboard'),


    path('result_dashboard/<str:grade>', views.result_dashboard, name='result_dashboard'),
    path('publish_result/', views.publish_result, name='publish_result'),


    path('student_update/<str:pk>', views.student_update, name='student_update'),
    path('teacher_update/<str:pk>', views.teacher_update, name='teacher_update'),
    path('parent_update/<str:pk>', views.parent_update, name='parent_update'),
    path('staff_update/<str:pk>', views.staff_update, name='staff_update'),


    path('student_profile/<str:pk>', views.student_profile, name='student_profile'),
    path('parent_profile/<str:pk>', views.parent_profile, name='parent_profile'),

    path('change_password', views.change_password, name='change_password'),
]

SchoolAdmin/announcement/models.py
from django.db import models
from base.models import *
# Create your models here.


class Announcement(models.Model):
    creator = models.ForeignKey(Staff, on_delete=models.CASCADE)
    title = models.CharField(max_length=70, null=False, blank=False)
    body = models.TextField(null=False, blank=False)
    timestamp = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title

SchoolAdmin/announcement/forms.py
from django import forms
from .models import *


class AnnouncementCreationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        for visible in self.visible_fields():
            visible.field.widget.attrs.update({
                'class': 'form-control',
                'placeholder': visible.field.label,
            })

    class Meta:
        model = Announcement
        fields = ['title', 'body']

SchoolAdmin/announcement/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from django.views.generic import CreateView, ListView, DetailView, DeleteView

from .models import *
from .forms import *
# Create your views here.

class AnnouncementList(LoginRequiredMixin, ListView):
    queryset = Announcement.objects.order_by('-timestamp')
    context_object_name = 'announcements'
    template_name = 'announcement/announcement.html'

    login_url = '/restricted/'

class CreateAnnouncement(CreateView, LoginRequiredMixin):
    model = Announcement
    form_class = AnnouncementCreationForm
    template_name = 'announcement/create_announcement.html'
    success_url = reverse_lazy('announcement:announcement')

    login_url = '/restricted/'

    def form_valid(self, form):
        form.instance.creator = self.request.user.staff

        return super().form_valid(form)

class DeleteAnnouncement(DeleteView, LoginRequiredMixin):
    model = Announcement
    context_object_name = 'announcement'
    template_name = 'announcement/delete_announcement.html'
    success_url = reverse_lazy('announcement:announcement')

    login_url = '/restricted/'

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'Announcement deleted successfully.')
        return super().delete(request, *args, **kwargs)

SchoolAdmin/announcement/templates/announcement/announcement.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} MTA School {% endblock %}

{% block content %}

<div class="container mx-0 mx-sm-5">
    <div class="row m-4 d-flex justify-content-around">
        <h2 class="p-1 col-auto">Announcements</h2>
        {% if request.user.is_staff %}
            <a href="{% url 'announcement:create_announcement' %}" class="col-auto btn btn-primary m-2">New Announcemnt</a>
        {% endif %}
        <hr>
    </div>
    <div class="shadow-lg p-0 p-sm-4">
        {% for message in messages %}
            <div class="alert {%if message.tags == 'success' %} alert-success {% else %} alert-danger {% endif %}">{{ message }}</div>
        {% endfor %}   
        {% if announcements.exists %}
            {% for i in announcements %}
                <div class="shadow-lg p-2 px-3 mb-3">
                    <h5 class="mb-3">{{i}}</h5>
                    <p class="announcement-body p-1 p-sm-3">
                        {{ i.body }} 
                    </p>
                    {% if request.user.is_staff %}
                            <a href="{% url 'announcement:delete_announcement' i.id %}" class="btn bg-danger text-light">Remove</a>
                    {% endif %}
                    
                    <hr class="m-0">
                    <p class="text-end mb-0"><i>{{i.creator}} | {{ i.timestamp }}</i></p>
                </div>
            {% endfor %}
        {% else %}
            <h3 class="mt-5 text-center text-danger">No Announcements Yet!</h3>
        {% endif %}
    </div>
</div> 

{% endblock %}

SchoolAdmin/announcement/templates/announcement/create_announcement.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} MTA School {% endblock %}

{% block content %}

<div class="container m-1 m-sm-5 p-4">
    <div class="shadow-lg p-4">
        <form method="post">
            {% csrf_token %}
    
            {% for message in messages %}
                <div class="alert {%if message.tags == 'success' %} alert-success {% else %} alert-danger {% endif %}">{{ message }}</div>
            {% endfor %}
    
            {% for field in form %}
            <label for="{{field.id_for_label}}">{{ field.label }}:</label>
                {{field}}
                
                {% if field.errors %}
                    {{field.errors|join:', '}}
                {% endif %}
            {% endfor %}
        
            <div class="class="d-grid gap-2 d-md-block"">
              <button type="submit" class="btn btn-primary mt-3 btn-block">Post</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

SchoolAdmin/announcement/templates/announcement/delete_announcement.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} MTA School {% endblock %}

{% block content %}

<div class="container m-1 m-sm-5 p-4">
    <div class="shadow-lg p-4">
        <p class="text-danger">
            Are you sure you want to delete {{ announcement }}?
        </p>
        <div class="row justify-content-center">
            <form action="" method="post" class="col">
                {% csrf_token %}
                <button class="btn btn-danger" type="submit">Delete</button>
            </form>
            <a href="{% url 'announcement:announcement' %}" class="col-auto bg-primary text-light d-flex align-items-center justify-content-center text-decoration-none">
                Cancel
            </a>
        </div>
    </div>
</div>

{% endblock %}