SchoolAdmin/SchoolAdmin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("base.urls", namespace='base')),
    path('announcement/', include("announcement.urls", namespace='announcement')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SchoolAdmin/base/urls.py
from django.urls import path
from . import views

app_name = 'base'


urlpatterns = [
    path('', views.home, name="home"),
    path('dashboard/', views.dashboard, name="dashboard"),

    path('student_academics/', views.student_academics, name='student_academics'),
    path('teacher_academics/', views.teacher_academics, name='teacher_academics'),
    
    path('restricted/', views.restricted_view, name='restricted'),
    path('student_login/', views.student_login, name='student_login'),
    path('teacher_login/', views.teacher_login, name='teacher_login'),
    path('staff_login/', views.staff_login, name='staff_login'),
    path('parent_login/', views.parent_login, name='parent_login'),
    path('logout/', views.logout_view, name='logout'),

    path('student_register/', views.student_register, name='student_register'),
    path('teacher_register/', views.teacher_register, name='teacher_register'),
    path('parent_register/', views.parent_register, name='parent_register'),
    path('staff_register/', views.staff_register, name='staff_register'),


    path('student_register_with_file/', views.student_register_with_file, name='student_register_with_file'),
    path('teacher_register_with_file/', views.teacher_register_with_file, name='teacher_register_with_file'),

    path('student_dashboard/<str:grade>', views.student_dashboard, name='student_dashboard'),
    path('teacher_dashboard/', views.teacher_dashboard, name='teacher_dashboard'),
    path('staff_dashboard/', views.staff_dashboard, name='staff_dashboard'),
    path('parent_dashboard/', views.parent_dashboard, name='parent_dashboard'),


    path('result_dashboard/<str:grade>', views.result_dashboard, name='result_dashboard'),
    path('publish_result/', views.publish_result, name='publish_result'),


    path('student_update/<str:pk>', views.student_update, name='student_update'),
    path('teacher_update/<str:pk>', views.teacher_update, name='teacher_update'),
    path('parent_update/<str:pk>', views.parent_update, name='parent_update'),
    path('staff_update/<str:pk>', views.staff_update, name='staff_update'),


    path('student_profile/<str:pk>', views.student_profile, name='student_profile'),
    path('parent_profile/<str:pk>', views.parent_profile, name='parent_profile'),

    path('change_password', views.change_password, name='change_password'),
]

SchoolAdmin/base/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *


class StudentCreationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        for visible in self.visible_fields():
            visible.field.widget.attrs.update({
                'class': 'form-control',
                'placeholder': visible.field.label,
            })

    first_name = forms.CharField(label='First Name', max_length=20, required=True)
    last_name = forms.CharField(label='Last Name', max_length=20, required=True)
    email = forms.EmailField(label='Email', required=False)

    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'email','image', 'age', 'gender', 'grade', 'parent_phone']

class TeacherCreationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        for visible in self.visible_fields():
            visible.field.widget.attrs.update({
                'class': 'form-control',
                'placeholder': visible.field.label,
            })

    first_name = forms.CharField(label='First Name', max_length=20, required=True)
    last_name = forms.CharField(label='Last Name', max_length=20, required=True)
    email = forms.EmailField(label='Email', required=False)

    class Meta:
        model = Teacher
        fields = ['first_name', 'last_name', 'email', 'gender', 'department', 'experience', 'phone']


class ParentCreationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        for visible in self.visible_fields():
            visible.field.widget.attrs.update({
                'class': 'form-control',
                'placeholder': visible.field.label,
            })

    first_name = forms.CharField(label='First Name', max_length=20, required=True)
    last_name = forms.CharField(label='Last Name', max_length=20, required=True)
    email = forms.EmailField(label='Email', required=False)
    parent_to = forms.ModelMultipleChoiceField(queryset=Student.objects.order_by('name'), required=False)
    class Meta:
        model = Parent
        autocomplete_fileds = ['parent_to']
        fields = ['first_name', 'last_name', 'email', 'parent_to', 'phone']


class StaffCreationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        for visible in self.visible_fields():
            visible.field.widget.attrs.update({
                'class': 'form-control',
                'placeholder': visible.field.label,
            })

    first_name = forms.CharField(label='First Name', max_length=20, required=True)
    last_name = forms.CharField(label='Last Name', max_length=20, required=True)
    email = forms.EmailField(label='Email', required=False)

    class Meta:
        model = Staff
        fields = ['first_name', 'last_name', 'email', 'gender', 'phone']


class ExcelImportForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        for visible in self.visible_fields():
            visible.field.widget.attrs.update({
                'class': 'form-control',
                'placeholder': visible.field.label,
            })
    file = forms.FileField(required=True)

class StudentCreationFormWithFile(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name', 'age', 'gender', 'grade', 'parent_phone']

class TeacherCreationFormWithFile(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['name', 'gender']

class ScoreForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        for visible in self.visible_fields():
            visible.field.widget.attrs.update({
                'class': 'form-control',
                'placeholder': visible.field.label,
            })
    SEMESTER_CHOICE =[
        ('First Semester', '1st'),
        ('Second Semester', '2nd')
    ]
    GRADE_CHOICES = [
        ('5', 'Grade 5'),
        ('6', 'Grade 6'),
        ('7', 'Grade 7'),
        ('8', 'Grade 8'),
        ('9', 'Grade 9'),
        ('10', 'Grade 10'),
    ]

    grade = forms.ChoiceField(choices=GRADE_CHOICES, required=True)
    semester = forms.ChoiceField(choices=SEMESTER_CHOICE, required=True)
    file = forms.FileField(required=True)
    

class PublishScoreForm(forms.ModelForm):
    class Meta:
        model = Score
        fields = ['semester' ,'physics', 'biology', 'chemistry', 'average', 'rank']

SchoolAdmin/base/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, HttpResponse, redirect, HttpResponsePermanentRedirect, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.models import User
from .models import *
from .forms import *
from .utils import *
from openpyxl import load_workbook

# Create your views here.

# base views section
def home(request):
    students = Student.objects.all()
    teachers = Teacher.objects.all()
    staffs = Staff.objects.all()

    female_students = Student.filter_by_gender('F')
    male_students = Student.filter_by_gender('M')

    female_teachers = Teacher.filter_by_gender('F')
    male_teachers = Teacher.filter_by_gender('M')
    
    female_staffs = Staff.filter_by_gender('F')
    male_staffs = Staff.filter_by_gender('M')
    
    context = {
        'teachers': teachers,
        'students': students,
        'staffs': staffs,

        'female_students': female_students,
        'male_students': male_students,

        'female_teachers': female_teachers,
        'male_teachers': male_teachers,

        'female_staffs': female_staffs,
        'male_staffs': male_staffs,
    }

    return render(request, 'base/home.html', context)


@login_required(login_url='/restricted/')
def student_academics(request):
    students = Student.objects.all()
    female = Student.filter_by_gender('F')
    male = Student.filter_by_gender('M')
    context = {
        'students': students,
        'female': female,
        'male': male,
    }

    return render(request, 'student_academics.html', context)

@login_required(login_url='/restricted/')
def teacher_academics(request):
    teachers = Teacher.objects.all()
    female = Teacher.filter_by_gender('F')
    male = Teacher.filter_by_gender('M')
    context = {
        'teachers': teachers,
        'female': female,
        'male': male,
    }
    return render(request, 'teacher_academics.html', context)



# Authentication views section
def logout_view(request):
    logout(request)

    return HttpResponsePermanentRedirect(reverse('base:home'))

def student_login(request):
    if request.method == 'POST':
        student_id = request.POST['student_id']
        password = request.POST['password']

        user = authenticate(request, student_id=student_id, password=password)
        if user:
            login(request, user)
            return redirect('base:home')
        else:
            error_message = 'Invalid ID number or Password'
            return render(request, 'login/student_login.html', {'error_message': error_message})
    else:
        return render(request, 'login/student_login.html')

def teacher_login(request):
    if request.method == 'POST':
        teacher_id = request.POST['teacher_id']
        password = request.POST['password']

        user = authenticate(request, teacher_id=teacher_id, password=password)
        if user:
            login(request, user)
            return redirect('base:home')
        else:
            error_message = 'Invalid ID number or Password'
            return render(request, 'login/teacher_login.html', {'error_message': error_message})
    else:
        return render(request, 'login/teacher_login.html')

def staff_login(request):
    if request.method == 'POST':
        staff_id = request.POST['staff_id']
        password = request.POST['password']

        user = authenticate(request, staff_id=staff_id, password=password)
        if user:
            login(request, user)
            if user.is_staff:
                return redirect('base:dashboard')
            else:
                return redirect('base:home')
        else:
            error_message = 'Invalid ID number or Password'
            return render(request, 'login/staff_login.html', {'error_message': error_message})
    else:
        return render(request, 'login/staff_login.html')

def parent_login(request):
    if request.method == 'POST':
        parent_id = request.POST['parent_id']
        password = request.POST['password']

        user = authenticate(request, parent_id=parent_id, password=password)
        if user:
            login(request, user)
            return redirect('base:home')
        else:
            error_message = 'Invalid ID number or Password'
            return render(request, 'login/parent_login.html', {'error_message': error_message})
    else:
        return render(request, 'login/parent_login.html')


@login_required
def change_password(request):
    if request.method == 'POST':
        current_password = request.POST['current_password']
        new_password = request.POST['new_password']
        confirm_password = request.POST['confirm_password']

        user = authenticate(username=request.user.username, password=current_password)
        if user:
            if new_password == confirm_password:
                user.set_password(new_password)
                user.save()
                login(request, user)
                messages.success(request, 'Password is successfully!')
                return redirect('base:home')
            else:
                messages.error(request, 'The New Password and Confirm Password do not match!')
                return redirect('base:change_password')
        else:
            messages.error(request, 'Wrong Password. Please try again!')
            return redirect('base:change_password')

    return render(request, 'dashboard/change_password.html')



# Dashboard Views section
@login_required
@user_passes_test(lambda user: user.is_staff)
def dashboard(request):
    students = Student.objects.all()
    teachers = Teacher.objects.all()
    staffs = Staff.objects.all()
    parents = Parent.objects.all()

    female_students = Student.filter_by_gender('F')
    male_students = Student.filter_by_gender('M')

    female_teachers = Teacher.filter_by_gender('F')
    male_teachers = Teacher.filter_by_gender('M')
    
    female_staffs = Staff.filter_by_gender('F')
    male_staffs = Staff.filter_by_gender('M')
    
    context = {
        'teachers': teachers,
        'students': students,
        'staffs': staffs,
        'parents': parents,

        'female_students': female_students,
        'male_students': male_students,

        'female_teachers': female_teachers,
        'male_teachers': male_teachers,

        'female_staffs': female_staffs,
        'male_staffs': male_staffs,
    }
    return render(request, 'dashboard/dashboard.html', context)



@login_required
@user_passes_test(lambda user: user.is_staff)
def student_dashboard(request, grade='all'):
    students = Student.objects.filter(grade=grade)
    if grade == 'all':
        students = Student.objects.all()
    students = students.order_by('name')
    context = {
        'students': students,
    }
    return render(request, 'dashboard/student_dashboard.html', context)


@login_required
@user_passes_test(lambda user: user.is_staff)
def teacher_dashboard(request):
    teachers = Teacher.objects.order_by('name')
    context = {
        'teachers': teachers,
    }
    return render(request, 'dashboard/teacher_dashboard.html', context)


@login_required
@user_passes_test(lambda user: user.is_staff)
def staff_dashboard(request):
    staffs = Staff.objects.order_by('name')
    context = {
        'staffs': staffs,
    }
    return render(request, 'dashboard/staff_dashboard.html', context)

@login_required
@user_passes_test(lambda user: user.is_staff)
def parent_dashboard(request):
    parents = Parent.objects.order_by('name')
    context = {
        'parents': parents,
    }
    return render(request, 'dashboard/parent_dashboard.html', context)


@login_required
@user_passes_test(lambda user: user.is_staff)
def student_register(request):
    if request.method == 'POST':
        form = StudentCreationForm(request.POST, request.FILES)
        if form.is_valid():
            print(form)
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            email = form.cleaned_data.get('email')
            username = first_name.strip().lower() + '_' + last_name.strip().lower()

            if User.objects.filter(username=username).exists():
                messages.error(request, f'{username} is already registered. Please choose a different username.')
            else:
                user = User.objects.create_user(
                    username=username, 
                    first_name=first_name, 
                    last_name=last_name,
                    email=email,
                    password='@@aa12345',
                )
                if user:
                    name = first_name + ' ' + last_name
                    image = form.cleaned_data['image']
                    grade = form.cleaned_data.get('grade')
                    age = form.cleaned_data.get('age')
                    gender = form.cleaned_data.get('gender')
                    parent_phone = form.cleaned_data.get('parent_phone')
                    student = Student(
                        user=user, 
                        name=name, 
                        image=image,
                        grade=grade, 
                        gender=gender,
                        age=age,
                        parent_phone=parent_phone,
                    )
                    if student:
                        student.save()
                        messages.success(request, f'{name} is registered successfully!')
                        return redirect('base:dashboard')
                    else:
                        user.delete()
                        messages.error(request, 'Someting went wrong while registering Student')
                        
                return redirect('base:student_register')
        else:
            messages.error(request, 'Someting went wrong while registering Student')
    else:

SchoolAdmin/base/templates/dashboard/dashboard.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} MTA School {% endblock %}

{% block content %}

<div class="container p-5">
    <div class="row d-flex justify-content-around">
        <h2 class="p-1 col-8">Dashboard</h2>
        <a href="{% url 'base:result_dashboard' 'all' %}" class="col-auto btn btn-primary mx-2">Result Dashboard</a>
    </div>
    <hr>
    <div class="shadow-xlg">
        {% for message in messages %}
            <div class="alert {%if message.tags == 'success' %} alert-success {% else %} alert-danger {% endif %}">{{ message }}</div>
        {% endfor %}
        <table class="table">
            <thead class="table-primary">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Occupation</th>
                <th scope="col">All</th>
                <th scope="col">Males</th>
                <th scope="col">Females</th>
            </tr>
            </thead>
            <tbody>
                <tr class="dashboard-row tr" href="{% url 'base:student_dashboard' 'all' %}">
                    <th scope="row">1</th>
                    <td>Students</td>
                    <td>{{ students.count }}</td>
                    <td>{{ male_students.count }}</td>
                    <td>{{ female_students.count }}</td>
                </tr>
                <tr class="dashboard-row tr" href="{% url 'base:teacher_dashboard'%}">
                    <th scope="row">2</th>
                    <td>Teachers</td>
                    <td>{{ teachers.count }}</td>
                    <td>{{ male_teachers.count }}</td>
                    <td>{{ female_teachers.count }}</td>
                </tr>
                <tr class="dashboard-row tr" href="{% url 'base:staff_dashboard' %}">
                    <th scope="row">3</th>
                    <td>Staffs</td>
                    <td>{{ staffs.count }}</td>
                    <td>{{ male_staffs.count }}</td>
                    <td>{{ female_staffs.count }}</td>
                </tr>
                <tr class="dashboard-row tr" href="{% url 'base:parent_dashboard' %}">
                    <th scope="row">4</th>
                    <td>Parents</td>
                    <td>{{ parents.count }}</td>
                    <td> - </td>
                    <td> - </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

SchoolAdmin/base/templates/dashboard/file_register_complete2.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} MTA School {% endblock %}

{% block content %}

<div class="container p-5">
    <div class="row mb-4 mx-2">
        <a href="{% url 'base:teacher_register' %}" class="col-5 btn btn-primary mx-2">Register New Teacher</a>
        <a href="{% url 'base:teacher_register_with_file' %}" class="col-5 btn btn-primary mx-2">Register With File</a>
    </div>
    <hr>
    <div class="shadow-xlg">
        {% if success_count == count %}
            <div class="alert alert-success">
                All Teachers are registered successfully!
            </div>
        {% elif success_count == 0 %}
            <div class="alert alert-danger">
                No Teachers are registed!
            </div>
        {% else %}
        <div class="alert alert-success">
            You have registered {{ success_count }} Teachers out of {{count}}.
        </div>
        {% endif %}
        {% if messages %}
            <button class="btn btn-danger mb-3" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">
                click to see Error messages.
            </button>
            <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
                <div class="offcanvas-header">
                    <h5 id="offcanvasRightLabel">Error messages</h5>
                    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    {% for message in messages %}
                        <div class="alert {%if message.tags == 'success' %} alert-success {% else %} alert-danger {% endif %}">{{ message }}</div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        <table class="table">
            <thead class="table-primary">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Teacher Id</th>
                <th scope="col">Gender</th>
                <th scope="col">Department</th>
                <th scope="col">experience</th>
                <th scope="col">Phone</th>
            </tr>
            </thead>
            <tbody>
                {% for teacher in teachers %}
                    {% if teacher.teacher_id in complete %}
                        <tr class="dashboard-row"  href="{% url 'base:teacher_update' teacher.teacher_id %}">
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ teacher.name }}</td>
                            <td>{{ teacher.teacher_id }}</td>
                            <td>{{ teacher.gender }}</td>
                            <td>{{ teacher.department }}</td>
                            <td>+{{ teacher.experience }} years</td>
                            <td>{{ teacher.phone }}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

SchoolAdmin/base/templates/dashboard/result_dashboard.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} MTA School {% endblock %}

{% block content %}

<div class="container p-5">
    <div class="row d-flex justify-content-around">
        <h2 class="p-1 col-7">Result Dashboard</h2>
        <a href="{% url 'base:publish_result'%}" class="col-auto btn btn-primary mx-2">Publish Result With Excel</a>
    </div>
    <hr>
    <div class="btn-group my-2">
        <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Filter by grade
        </button>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'base:result_dashboard' 'all' %}">All</a></li>
            <li><a class="dropdown-item" href="{% url 'base:result_dashboard' 5 %}">5</a></li>
            <li><a class="dropdown-item" href="{% url 'base:result_dashboard' 6 %}">6</a></li>
            <li><a class="dropdown-item" href="{% url 'base:result_dashboard' 7 %}">7</a></li>
            <li><a class="dropdown-item" href="{% url 'base:result_dashboard' 8 %}">8</a></li>
            <li><a class="dropdown-item" href="{% url 'base:result_dashboard' 9 %}">9</a></li>
            <li><a class="dropdown-item" href="{% url 'base:result_dashboard' 10 %}">10</a></li>
        </ul>
    </div>
    <div class="shadow-xlg">
        {% for message in messages %}
            <div class="alert {%if message.tags == 'success' %} alert-success {% else %} alert-danger {% endif %}">{{ message }}</div>
        {% endfor %}
        <table class="table">
            <thead class="table-primary">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Student Id</th>
                <th scope="col">Grade</th>
                <th scope="col">Average</th>
                <th scope="col">Rank</th>
            </tr>
            </thead>
            <tbody>
                {% for student in students %}
                    <tr class="dashboard-row" href="{% url 'base:student_update' student.student_id %}">
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ student.name }}</td>
                        <td>{{ student.student_id }}</td>
                        <td>{{ student.grade }}</td>
                        {% with score=student.scores.all|first %}
                            {% if score %}
                                <td>{{ score.average }}</td>
                                <td>{{ score.rank }}</td>
                            {% else %}
                                <td class="text-danger">Not Published</td>
                                <td class="text-danger">Not Pulbished</td>
                            {% endif %}
                        {% endwith %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

SchoolAdmin/base/templates/dashboard/student_dashboard.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} MTA School {% endblock %}

{% block content %}

<div class="container p-5">
    <div class="row d-flex justify-content-around">
        <h2 class="p-1 col-8">Student Dashboard</h2>
        <a href="{% url 'base:result_dashboard' 'all' %}" class="col-auto btn btn-primary mx-2">Result Dashboard</a>
    </div>
    <hr>
    <div class="row mb-4 mx-2 justify-content-around">
        <a href="{% url 'base:student_register' %}" class="col-5 btn btn-primary mx-2">Register New Student</a>
        <a href="{% url 'base:student_register_with_file' %}" class="col-5 btn btn-primary mx-2">Register With File</a>
    </div>
    <div class="btn-group my-2">
        <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Filter by grade
        </button>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'base:student_dashboard' 'all' %}">All</a></li>
            <li><a class="dropdown-item" href="{% url 'base:student_dashboard' 5 %}">5</a></li>
            <li><a class="dropdown-item" href="{% url 'base:student_dashboard' 6 %}">6</a></li>
            <li><a class="dropdown-item" href="{% url 'base:student_dashboard' 7 %}">7</a></li>
            <li><a class="dropdown-item" href="{% url 'base:student_dashboard' 8 %}">8</a></li>
            <li><a class="dropdown-item" href="{% url 'base:student_dashboard' 9 %}">9</a></li>
            <li><a class="dropdown-item" href="{% url 'base:student_dashboard' 10 %}">10</a></li>
        </ul>
    </div>
    <div class="shadow-xlg">
        {% for message in messages %}
            <div class="alert {%if message.tags == 'success' %} alert-success {% else %} alert-danger {% endif %}">{{ message }}</div>
        {% endfor %}
        <table class="table">
            <thead class="table-primary">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Student Id</th>
                <th scope="col">Grade</th>
                <th scope="col">Gender</th>
                <th scope="col">Age</th>
                <th scope="col">Parent Phone</th>
            </tr>
            </thead>
            <tbody>
                {% for student in students %}
                    <tr class="dashboard-row" href="{% url 'base:student_update' student.student_id %}">
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ student.name }}</td>
                        <td>{{ student.student_id }}</td>
                        <td>{{ student.grade }}</td>
                        <td>{{ student.gender }}</td>
                        <td>{{ student.age }}</td>
                        <td>{{ student.parent_phone }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

SchoolAdmin/base/templates/dashboard/teacher_dashboard.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %} MTA School {% endblock %}

{% block content %}
 
<div class="container p-5">
    <h2 class="p-1">Teachers of MTA</h2>
    <hr>
    <div class="row d-flex justify-content-around mb-4 mx-2">
        <a href="{% url 'base:teacher_register' %}" class="col-5 btn btn-primary mx-2">Register New Teacher</a>
        <a href="{% url 'base:teacher_register_with_file' %}" class="col-5 btn btn-primary mx-2">Register With File</a>
    </div>
    <div class="shadow-xlg">
        {% for message in messages %}
            <div class="alert {%if message.tags == 'success' %} alert-success {% else %} alert-danger {% endif %}">{{ message }}</div>
        {% endfor %}
        <table class="table">
            <thead class="table-primary">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Teacher Id</th>
                <th scope="col">Gender</th>
                <th scope="col">Department</th>
                <th scope="col">experience</th>
                <th scope="col">Phone</th>
            </tr>
            </thead>
            <tbody>
                {% for teacher in teachers %}
                    <tr class="dashboard-row"  href="{% url 'base:teacher_update' teacher.teacher_id %}">
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ teacher.name }}</td>
                        <td>{{ teacher.teacher_id }}</td>
                        <td>{{ teacher.gender }}</td>
                        <td>{{ teacher.department }}</td>
                        <td>+{{ teacher.experience }} years</td>
                        <td>{{ teacher.phone }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}